AllCops:
  Exclude:
    - spec/spec_helper.rb

Naming/MethodParameterName:
  MinNameLength: 1
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  Max: 100
Metrics/ModuleLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 20

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
